language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    rooms:
      - secure: LUWpQVnO7je+q8gbbUsYbSsneKuUVSAnA5gTF/TxCKF8YQ2K1DT4VK1sJhOpwNFu3x41KYClKhIBZ0R+UPEgcr8OD99cK7DfWQpKG3vwXi+IQleNGzxosqL7Viw+VFWMWSGdUrMSAP9/e6eep84mjFERGxxevt6NIOlPm8WPhEdD2tHW5/PQVwdEwtAAt8AViuIkMN53S9A4w9XmnjMnrqadMiuX+JEh9+DC9PDVuT1RrkByxP+HxblFrYoJH2Achv2OpYF4XZvqiEaH+oe2kCwFcmItWgrg7UvxDVXr57zhfXtWL47nNySX+ZecRwmWRi1UQwiSQfk/zZNKc9EquhZNHrgUOCJbSe5WluJpogG2r/pHL2zL8BAgPDb+HUrJ7CoWIm0CCVP+UiEnalCyGHpowzekmHvg4etlYtDuOX4iGzyxSBCKq+Z3+91q7nL4laNNEPtPgf0aGIV0EWHf4jJaqJ2afLTbuhTrpLsTJpwL7EfXOGuYT2FMys5t4ahq7N9STM1qdgJdopOQlaT3V1za03WB3kNXx+ZOkro3mFZiliIjS4FnRhJUJZcOnzHhOC4AHjAFxuvh5rCSZ/GlVX1/lDyd/cc42kYZYpXDsks47A4+Sh/URJkxl9cqnkz4syWg2eirmyWhZH8ju1adkxTHPdsUdD+dNEPB3Bo2hwA=
    on_success: change
    on_failure: always
